--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/TungstenVn/TradePP
projects:
  TradePeople:
    path: TradePeople/
    - src: muqsit/InvMenu/InvMenu
        version: ^2.0.0
        branch: master
...
